openapi: 3.0.0
info:
  description: "This is a sample API for retrieving Prices"
  version: "1.0.0-SNAPSHOT"
  title: "Price API"
servers:
  - url: http://localhost:8080/api/v1
    description: "Local test server"
tags:
  - name: "prices"
    description: "Prices operations"
paths:
  /prices:
    get:
      tags:
        - "prices"
      summary: This operation obtains a price given the provided parameters
      description: Retrieves a price based on the brandId, productId and applicationDate
      operationId: priceRetrievalBy
      parameters:
        - in: query
          name: brandId
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
          description: Desired brand
          example: 1
        - in: query
          name: productId
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
          description: Desired product
          example: 35455
        - in: query
          name: applicationDate
          required: true
          schema:
            type: string
            format: date-time
          description: Application date on ISO format with timezone
          example: "2020-06-14T00:00:00Z"
      responses:
        '200':
          description: Succesful price retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    PriceResponse:
      type: object
      properties:
        brandId:
          type: integer
          format: int64
          example: 1
        productId:
          type: integer
          format: int64
          example: 35455
        startDate:
          type: string
          format: date-time
          example: "2020-06-14T00:00:00Z"
        endDate:
          type: string
          format: date-time
          example: "2020-12-31T23:59:59Z"
        applicablePrice:
          type: string
          format: decimal
          example: 35.50
        currency:
          type: string
          example: "EUR"
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Error"
        details:
          type: array
          items:
            type: string
        timestamp:
          type: string
          format: date-time